### ISSUE TITLE
LrMediaWiki still includes coordinates in the file page when 'Remove Location Info' is selected

### ISSUE THREAD

**Issue by mpeel** [Hasenlaeufer/LrMediaWiki#41]
When uploading a file with LrMediaWiki, you have the option to 'Remove Location Info' under 'Metadata'. However, after uploading, the file information page still includes the coordinates, even though they have been removed from the Exif. This can be a privacy concern.

Expected behaviour: if 'Remove Location Info' is selected, then no coordinates should be uploaded, either in the fire information or in the metadata.

**Comment by Hasenlaeufer** [comment]
Go to File -> Plug-In Manager… -> LrMediaWiki -> LrMediaWiki Configuration and set the switch "Enable {{Location}} template" to "off".

**Comment by mpeel** [comment]
I normally want to include the location template for the photographs I upload, since that is really important for matching the photographs to the location they were taken at. However, for specific photos that I've taken at home, I don't want to upload their location - which is when I select 'Remove location info'.

**Comment by Hasenlaeufer** [comment]
LrMediaWiki is not able to detect the setting of the switch "Remove location info", because it is out of scope of the plugin and there is no possibility by the SDK to read the setting. Therefore the extra switch at configuration dialogue. Sorry for this inconvenience.

**Comment by mpeel** [comment]
It's being displayed through the plugin upload interface, and it needs to be handled on a per-upload-batch level, not at the plugin configuration level. If this is a problem with Lightroom itself, then I'd be happy to support a bug report there about this - but I don't known how to post such a bug report to Adobe myself.

**Comment by Hasenlaeufer** [comment]
There are good news. I found a way to read the value of the checkbox "Remove Location Info". It was a bit tricky – however, it works. This means, we can get rid of the extra checkbox at configuration dialog and rely solely on the checkbox provided at metadata section.

**Comment by Hasenlaeufer** [comment]
In detail, the upcoming release 1.4 will include this enhancement:

The checkbox "Enable {{Location}} template" at configuration dialog is obsolete and has been removed. It was a workaround due to a lack of the Lightroom SDK and was introduced by version 1.0.2, see issue #13 ("Do not fill location template if 'Remove Location Info' is checked").

The SDK-lack is still existent, but now there is another workaround which results in a smarter solution.
Now there is only one checkbox at export dialog: "Remove Location Info" at Metadata section. Its setting results in both:
  a) The generation of a {{Location}} template will be done if the checkbox is unset.
  b) The GPS coordinates at metadata section of the generated file description page are only shown if the checkbox is unset.
If the checkbox is set, both appearances are suppressed – location info is removed.

**Comment by Hasenlaeufer** [comment]
Implemented with version 1.4.

**Comment by mpeel** [comment]
That's great, thanks for finding and implementing a solution!
